### ISSUE TITLE
RMStepsController Freezing after pressing buttons un StepsBar and returning to 1

### ISSUE THREAD

**Issue by ibjazz** [CooperRS/RMStepsController#26]
Great Control! However I am having trouble when it suddenly freezes after returning to step number 1. I am using storyboards and instatiating tableviewcontrollers as well as uiviewcontrollers. I have the NavigationController presented modally and the my Custom StepsControllers as its rootviewcontroller. I get the following error:

malloc: *** mach_vm_map(size=8388608) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug

Please advise and thanks in advance!

**Comment by CooperRS** [comment]
The ticket author is not responding => Closing the ticket...
