### ISSUE TITLE
Pass information

### ISSUE THREAD

**Issue by ibjazz** [CooperRS/RMStepsController#29]
Hi! How can I pass information in order to prepare the next view of the step controller. I would usually use prepareForSegue, but in this case, there is actually no segue. All view controller are instantiated from the StepsController. So how can I prepare the new view. Thanks in advance.

**Comment by ibjazz** [comment]
Ok, I just did it from the StepsController since there is the view controller instantiated.

**Comment by CooperRS** [comment]
You may also take a look at #22. There I explained how to save information to the steps view controller by using the results dictionary the steps view controller offers. This information can be read by later view controllers.

**Comment by ibjazz** [comment]
Great Advise! Thanks! It helped a lot!
