### ISSUE TITLE
iOS8: Animation bug while sliding to next controller

### ISSUE THREAD

**Issue by tilowestermann** [CooperRS/RMStepsController#30]
There seems to be a bug in `showStepViewControllerWithSlideInAnimation:`: when proceeding to another step, views are overlapping. Couldn't figure out what exactly goes wrong.

**Comment by CooperRS** [comment]
Is the issue reproducible with every iPhone model? Is it possible to reproduce this issue with the current demo project (as it is optimized for iPhone 6 and 6+)?

**Comment by tilowestermann** [comment]
Apparently I posted this too early. It is not reproducible with the demo project (still using the UnlimitedSteps branch). Thanks for the quick reply!
