### ISSUE TITLE
change toolbar position

### ISSUE THREAD

**Issue by bubudrc** [CooperRS/RMStepsController#33]
Hi...

How can I change the position of the toolbar from top to bottom?

**Comment by CooperRS** [comment]
Hi,

with the current version you can't (at least out of the box).

If you want to extend RMStepsController you will have to change the way how RMStepsController layouts the RMStepsBar and the content view controller (RMStepsController.m viewDidLoad). In addition, you will have to change the way how the top and bottom layout guides for the content view controller are calculated (again RMStepsController.m).

Best regards,
Roland
