### ISSUE TITLE
Property synthesis

### ISSUE THREAD

**Issue by tilowestermann** [CooperRS/RMStepsController#35]
I'm using `RMStepsController` in [QULQuestionnaire](https://github.com/QULab/QULQuestionnaire-iOS). However, I'm not able to push a new version to the trunk of CocoaPods, as I'm getting the following warning:

```RMStepsController/RMStepsController/RMStepsBar.h:91:52: warning: auto property synthesis will not synthesize property 'delegate'; it will be implemented by its superclass, use @dynamic to acknowledge intention```

Side note: How did you manage to push a new version of `RMStepsController` to the trunk with this warning?

**Comment by CooperRS** [comment]
That's because I did not push a new version for a long time. Last time I pushed a version, Xcode did not throw this warning.

**Comment by CooperRS** [comment]
I pushed a fix for the warning :)

**Comment by tilowestermann** [comment]
Great, thanks! Unfortunately, you'd have to tag the new version in order to be accessible in a pod spec.
