### ISSUE TITLE
How do i jump from step 4 to step 1 or step 1 to step 4 if 2 and 3 are completed?

### ISSUE THREAD

**Issue by hardikamal** [CooperRS/RMStepsController#36]
Hi @CooperRS Thanks for the awesome library.....Is there any way where i can jump back from step 4 to step 1 or step 1 to step 4 if 2 abd 3 are completed onclicking the steps....

**Comment by CooperRS** [comment]
No, the library assumes, that when your are in step 4 and jump back to step 1 your have to re-do step 2 and 3 as the options you have in these steps might have changed.
