### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by abiaad** [CooperRS/RMStepsController#42]
Is it possible to support Carthage ? 
Thanks

**Comment by CooperRS** [comment]
HI there,

Should be possible. All you need is a framework target containing the classes that belong to `RMStepsController`.

I'll try to get to it in the next week 🙂 

Roland

**Comment by CooperRS** [comment]
Hey again!

The current `HEAD` of the `master`branch now contains a framework called `RMStepsController`. Could you try Carthage support with that commit?

Roland

**Comment by abiaad** [comment]
Hi Roland,

I made a [pull request](https://github.com/CooperRS/RMStepsController/pull/43) to fully support Carthage :)

It seems to work fine.

After merged, you can release a 1.0.3 if you want.

Thx

**Comment by CooperRS** [comment]
Fixed with https://github.com/CooperRS/RMStepsController/releases/tag/1.0.3
