### ISSUE TITLE
Views are under stepBar

### ISSUE THREAD

**Issue by grifas** [CooperRS/RMStepsController#45]
The views of my controllers are under the stepBar. How can I remake the constraints ?

**Comment by CooperRS** [comment]
Hi there!

You can override `- (void)adaptToEdgeInsets:(UIEdgeInsets)newInsets` in your view controllers you are presenting with `RMStepsController`. This tells you where the steps bar is and makes it possible for you to adjust your constraints.

For example, [`RMStepsController.m` contains a category on `UITableViewController`](https://github.com/CooperRS/RMStepsController/blob/master/RMStepsController/RMStepsController.m#L301) for adjusting the `UITableView` content insets based on where the steps bar is.

**Comment by grifas** [comment]
I have an issue with `- (void)adaptToEdgeInsets:(UIEdgeInsets)newInsets`. The first controller receive a bad edgeInsets (0 for top, left, right and bottom). The others controllers receive the right edgeInsets.

**Comment by CooperRS** [comment]
Hmm, I have seen that issue before, too. But I wasn't able to reproduce it. Do you have some more information? For example a demo project?
